spring:
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
facebook:
  graph.url: https://graph.facebook.com/v2.11/me
management:
  context-path: /mx
endpoints:
  sensitive: false
  enabled: true
  info:
    enabled: true
server.port: 80